name: Code Quality Check and Dependency Installation

on:
 push:
    branches:
      - dev

jobs:
 flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flask pandas pytest scikit-learn seaborn matplotlib xgboost scipy
      - name: Run flake8
        run: flake8 .
